version: '2'
services:
  influxdb:
    image: docker.io/bitnami/influxdb:2
    restart: always
    container_name: influxdb
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=admin2023
      - INFLUXDB_ADMIN_USER_TOKEN=admin
    volumes:
      - influxdb_data:/bitnami/influxdb
  postgres:
    image: docker.io/bitnami/postgresql:12
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=scale
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  influxdb_data:
    driver: local
  postgres_data:
    driver: local
