---
protocol-key-pair: Vsgn0iJaIz2vcMmNICAjNU4sC3a77ufjXaxkyc86UkSPxlXayEeWWkS8aStbaxPIzgeJnakQYVn83FgedD+ICQZdu9zEmznwUrJaeejFgzYIOQBn/Ss382I3d21zKI9yWfbqccLqWZqmNgSxS43MOz2ld5S37HhGhp81JDD/UA0=
worker-key-pair: CuHOpPuzoFkYCUczPy+FsiAvzha9v5t1F3bmByPHwTfcHr34/zEkA2ii4s/+Rjj6QDSFEbSOJijIgnkWKhl7rg==
account-key-pair: AEOhGbDuv7kR9aHEpWGtQvvhhMjPsv926ED0LS0ZQ8yXFJtjc+X44nj9X5aEje5fE/043ixGu7iGhFrk3hIe73M=
network-key-pair: RiYE8XvBBIRsifaylpaetsGetG2Sbxk0/BweZEj+E3Kr11FTOX1kD9uO55w7O7VDxveKetrtzFwJ+f6Iz0wQSA==
db-path: local/authorities_db/8fc655dac847965a44bc692b5b6b13c8ce07899da9106159fcdc581e743f8809065dbbdcc49b39f052b25a79e8c5833608390067fd2b37f36237776d73288f7259f6ea71c2ea599aa63604b14b8dcc3b3da57794b7ec7846869f352430ff500d
network-address: /ip4/127.0.0.1/tcp/51339/http
json-rpc-address: "127.0.0.1:51401"
metrics-address: "127.0.0.1:51397"
admin-interface-port: 51399
consensus-config:
  address: /ip4/127.0.0.1/tcp/51347/http
  db-path: local/consensus_db/8fc655dac847965a44bc692b5b6b13c8ce07899da9106159fcdc581e743f8809065dbbdcc49b39f052b25a79e8c5833608390067fd2b37f36237776d73288f7259f6ea71c2ea599aa63604b14b8dcc3b3da57794b7ec7846869f352430ff500d
  internal-worker-address: ~
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/51389/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/51391/http
    network_admin_server:
      primary_network_admin_server_port: 51393
      worker_network_admin_server_base_port: 51395
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:51341"
  external-address: /ip4/127.0.0.1/udp/51341
genesis:
  genesis-file-location: local/genesis.blob
