version: '3.1'
services:
  influxdb:
    image: docker.io/bitnami/influxdb:2
    restart: always
    container_name: influxdb
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=admin2023
      - INFLUXDB_ADMIN_USER_TOKEN=admin
    volumes:
      - influxdb_data:/bitnami/influxdb
volumes:
  influxdb_data:
    driver: local
